efiSystemPartition: "/boot"
efiSystemPartitionSize: 512M
userSwapChoices:
 - none
 - small
 - suspend
defaultFileSytemType: "ext4"
availableFileSystemTypes: ["ext4", "btrfs"]
partitionLayout:
 - name: "efi"
   filesystem: "fat32"
   mountPoint: "/boot"
   size: 512M
   flags: [ esp, boot ]
 - name: "root"
   filesystem: "ext4"
   mountPoint: "/"
   size: 100%
enableLuksAutomatedPartitioning: true
allowManualPartitioning: true
drawNestedPartitions: false
alwaysShowPartitionLabels: true
