defaultGroups:
  - name: wheel
    mustExist: true
    system: false
autologinGroup: autologin
doAutologin: false
sudoersGroup: wheel
setRootPassword: true
doReusePassword: false
passwordRequirements:
  minLength: 4
